import type { Metadata } from "next";
import localFont from "next/font/local";
import { Merriweather_Sans, Bebas_Neue } from "next/font/google"; // Update this line
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const merriweatherSans = Merriweather_Sans({
    weight: "400", // You can specify other weights if needed
    subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
    weight: "400", // You can specify other weights if needed
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Collosus Auto Collision",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${merriweatherSans.variable} ${bebasNeue.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
