import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto_Condensed } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const robotoCondensed = Roboto_Condensed({
    weight: ["400", "700"], // Roboto Condensed has multiple weights
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Collosus Auto Collision",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
